import { pgTable, text, serial, integer, boolean, timestamp, jsonb } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  token: text("token").notNull().unique(),
  xp: integer("xp").default(0).notNull(),
  level: integer("level").default(1).notNull(),
  currentModuleId: text("current_module_id"),
  currentStepIndex: integer("current_step_index").default(0).notNull(),
  totalSats: integer("total_sats").default(0).notNull(),
  independenceProgress: integer("independence_progress").default(0).notNull(),
});

export const insertUserSchema = createInsertSchema(users).omit({ id: true });
export type User = typeof users.$inferSelect;
export type InsertUser = z.infer<typeof insertUserSchema>;

export const sessions = pgTable("sessions", {
  id: serial("id").primaryKey(),
  nodeId: text("node_id").notNull(), // e.g. "#RE_CHAIN_1234"
  independenceScore: integer("independence_score").default(0).notNull(),
  currentStepId: text("current_step_id").notNull(),
  history: jsonb("history").$type<string[]>().default([]), // List of action IDs taken
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertSessionSchema = createInsertSchema(sessions).omit({
  id: true,
  createdAt: true,
  history: true
});

export type Session = typeof sessions.$inferSelect;
export type InsertSession = z.infer<typeof insertSessionSchema>;

export type CreateSessionRequest = {
  nodeId?: string; // Optional, can be generated by server
};

export type UpdateSessionRequest = {
  actionId: string;
  scoreDelta: number;
  nextStepId: string;
};

export type SessionResponse = Session;
