import { pgTable, text, serial, integer, boolean, timestamp, jsonb } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  token: text("token").notNull().unique(),
  xp: integer("xp").default(0).notNull(),
  level: integer("level").default(1).notNull(),
  currentModuleId: text("current_module_id"),
  currentStepIndex: integer("current_step_index").default(0).notNull(),
  totalSats: integer("total_sats").default(0).notNull(),
  independenceProgress: integer("independence_progress").default(0).notNull(),
});

export const insertUserSchema = createInsertSchema(users).omit({ id: true });
export type User = typeof users.$inferSelect;
export type InsertUser = z.infer<typeof insertUserSchema>;

export const sessions = pgTable("sessions", {
  id: serial("id").primaryKey(),
  nodeId: text("node_id").notNull(), // e.g. "#RE_CHAIN_1234"
  independenceScore: integer("independence_score").default(0).notNull(),
  currentStepId: text("current_step_id").notNull(),
  history: jsonb("history").$type<string[]>().default([]), // List of action IDs taken
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertSessionSchema = createInsertSchema(sessions).omit({
  id: true,
  createdAt: true,
  history: true
});

export type Session = typeof sessions.$inferSelect;
export type InsertSession = z.infer<typeof insertSessionSchema>;

export type CreateSessionRequest = {
  nodeId?: string; // Optional, can be generated by server
};

export type UpdateSessionRequest = {
  actionId: string;
  scoreDelta: number;
  nextStepId: string;
};

export type SessionResponse = Session;

export const SKILL_KEYS = ["WILL_TO_FREEDOM", "TRUTH_SEEKER", "HARD_MONEY", "GRID_RUNNER"] as const;
export type SkillKey = typeof SKILL_KEYS[number];

type LangKey = "IT" | "EN" | "RU";

export const SKILL_META: Record<SkillKey, { name: Record<LangKey, string>; description: Record<LangKey, string>; layer: string }> = {
  WILL_TO_FREEDOM: {
    name: { IT: "Volont\u00e0 di Libert\u00e0", EN: "Will to Freedom", RU: "\u0412\u043e\u043b\u044f \u043a \u0421\u0432\u043e\u0431\u043e\u0434\u0435" },
    description: { IT: "Hai fatto il primo passo. Protocollo attivato.", EN: "You took the first step. Protocol activated.", RU: "\u0422\u044b \u0441\u0434\u0435\u043b\u0430\u043b \u043f\u0435\u0440\u0432\u044b\u0439 \u0448\u0430\u0433. \u041f\u0440\u043e\u0442\u043e\u043a\u043e\u043b \u0430\u043a\u0442\u0438\u0432\u0438\u0440\u043e\u0432\u0430\u043d.",  },
    layer: "core",
  },
  TRUTH_SEEKER: {
    name: { IT: "Cercatore di Verit\u00e0", EN: "Truth Seeker", RU: "\u0418\u0441\u043a\u0430\u0442\u0435\u043b\u044c \u0418\u0441\u0442\u0438\u043d\u044b" },
    description: { IT: "Vedi attraverso le bugie del sistema. Visore attivato.", EN: "You see through the system's lies. Visor activated.", RU: "\u0422\u044b \u0432\u0438\u0434\u0438\u0448\u044c \u0441\u043a\u0432\u043e\u0437\u044c \u043b\u043e\u0436\u044c \u0441\u0438\u0441\u0442\u0435\u043c\u044b. \u0412\u0438\u0437\u043e\u0440 \u0430\u043a\u0442\u0438\u0432\u0438\u0440\u043e\u0432\u0430\u043d." },
    layer: "visor",
  },
  HARD_MONEY: {
    name: { IT: "Denaro Solido", EN: "Hard Money", RU: "\u0422\u0432\u0451\u0440\u0434\u044b\u0435 \u0414\u0435\u043d\u044c\u0433\u0438" },
    description: { IT: "Hai capito l'essenza del denaro reale. La chiave \u00e8 nelle tue mani.", EN: "You understood the essence of real money. The key is in your hands.", RU: "\u0422\u044b \u043f\u043e\u043d\u044f\u043b \u0441\u0443\u0442\u044c \u0437\u0432\u043e\u043d\u043a\u043e\u0439 \u043c\u043e\u043d\u0435\u0442\u044b. \u041a\u043b\u044e\u0447 \u0432 \u0442\u0432\u043e\u0438\u0445 \u0440\u0443\u043a\u0430\u0445." },
    layer: "hand_item",
  },
  GRID_RUNNER: {
    name: { IT: "Corridore della Rete", EN: "Grid Runner", RU: "\u0411\u0435\u0433\u0443\u0449\u0438\u0439 \u043f\u043e \u0421\u0435\u0442\u043a\u0435" },
    description: { IT: "Hai padroneggiato la rete Lightning. Aura della resistenza digitale.", EN: "You mastered the Lightning Network. Digital resistance aura.", RU: "\u0422\u044b \u043e\u0441\u0432\u043e\u0438\u043b \u0441\u0435\u0442\u044c Lightning. \u0410\u0443\u0440\u0430 \u0446\u0438\u0444\u0440\u043e\u0432\u043e\u0433\u043e \u0441\u043e\u043f\u0440\u043e\u0442\u0438\u0432\u043b\u0435\u043d\u0438\u044f." },
    layer: "aura",
  },
};

export const userSkills = pgTable("user_skills", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull(),
  skillKey: text("skill_key").notNull(),
  grantedAt: timestamp("granted_at").defaultNow(),
});

export const insertUserSkillSchema = createInsertSchema(userSkills).omit({ id: true, grantedAt: true });
export type UserSkill = typeof userSkills.$inferSelect;
export type InsertUserSkill = z.infer<typeof insertUserSkillSchema>;
